github:
  description: "Emails at the heart of your business logic!"
  homepage: https://james.apache.org/
  labels:
    - mail
    - server
    - imap
    - smtp
    - jmap

notifications:
  commits:      notifications@james.apache.org
  issues:       notifications@james.apache.org
  pullrequests: notifications@james.apache.org
  jira_options: link label comment